name: portfolio
services:
  web:
    image: nginx:mosi
    hostname: webserver
    ports:
      - 8081:80
    depends_on:
      - wordpress
    networks:
      - front
      - backend

  wordpress:
    image: bitnami/wordpress:latest
    hostname: wordpress
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_USERNAME=mosi
      - WORDPRESS_PASSWORD=hibiwith
      - WORDPRESS_DATABASE_HOST=db
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - backend
    
  db:
    image: bitnami/mariadb:latest
    hostname: database
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=somewordpress
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_wordpress
    networks:
      - backend

volumes:
  mariadb_data:
  wordpress_data:

networks:
  front:
  backend: